### ISSUE TITLE
ODF metrics not visble when used on ODF managed services Provider cluster

### ISSUE THREAD

**Issue by shekharberry** [pcuzner/odf-grafana#9]
On deploying grafana on ODF provider in ODF managed service environment, most of the charts on ODF performance analysis dashboard is empty.
Some sparse data can be seen in CEPH mem/CPU charts but otherwise most of the charts in the dashboard is empty.

On the other hand, if I run the Prom Query in OCP metrics page, I can see the data from there.

**Comment by pcuzner** [comment]
@shekharberry This is due to user namespace monitoring. ROSA uses user workload monitoring, which means access to the data needs to go through the thanos querier, instead of directly to prometheus. I've updated your environment - please check and if this resolves the issue I'll patch the playbook to allow for this type of configuration.

**Comment by shekharberry** [comment]
Thank you for looking into it. I redeployed the Grafana and I still don't see the data in the panels. Should I not have redeployed and used the old deployment?? Sorry if I messed up..

**Comment by pcuzner** [comment]
This should now be fixed. Closing for now.

**Comment by shekharberry** [comment]
I deployed a new ROSA cluster and I am seeing the same issue here again. I have used the latest playbook which should have the code change.
I don't see any data in the dashboards.
